[package]
name = "git_auto_logger"
version = "0.1.0"
edition = "2021"
authors = "Pedro Soares"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# make dev optimsation 3
[profile.dev]
opt-level = 3